# -*- coding: utf-8 -*-
"""temp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NumaDBGbkxP9PwTFyTb73b0zdTx3F2vR
"""

print("การแปลงอุณหภูมิ")

def celsius_to_fahrenheit (celsius) :
  return  (celsius*9/5)+32

def celsius_to_kelvin (celsius) :
  return  celsius+273.15


def fahrenheit_to_celsius (fahrenheit) :
  return  5/9*(fahrenheit-32)

def fahrenheit_to_kelvin (fahrenheit) :
  return  5/9*(fahrenheit-32)+273.15


def kelvin_to_celsius (kelvin) :
  return kelvin-273.15

def kelvin_to_fahrenheit (kelvin) :
  return 9/5*(kelvin-273.15)+32


print("เลือกหน่วยอุณหภูมิที่ท่านต้องการแปลง")
print("1: celsius -> fahrenheit/kelvin")
print("2: fahrenheit -> celsius/kelvin")
print("3: kelvin -> celsius/fahrenheit")


choice = input("ป้อนหมายเลขที่ต้องการ (1,2,3) : ")

temperature = float(input("ป้อนค่าอุณหภูมิ: "))


if choice == "1" :

             print(f"{temperature} C เท่ากับ {celsius_to_fahrenheit(temperature) : .1f} F และ {celsius_to_kelvin(temperature) : .2f} K")

elif choice == "2" :

             print(f"{temperature} F เท่ากับ {fahrenheit_to_celsius(temperature) : .1f} C และ {fahrenheit_to_kelvin(temperature) : .2f} K")

elif choice == "3" :

            print(f"{temperature} K เท่ากับ {kelvin_to_celsius(temperature) : .1f} C และ {kelvin_to_fahrenheit(temperature) : .1f} F")

else :

    print("กรุณาเลือกหมายเลขที่ถูกต้อง!")